# Generated by Django 5.0.6 on 2025-12-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StudentCognitiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_accuracy', models.FloatField(default=0.0)),
                ('understand_accuracy', models.FloatField(default=0.0)),
                ('apply_accuracy', models.FloatField(default=0.0)),
                ('analyse_accuracy', models.FloatField(default=0.0)),
                ('evaluate_accuracy', models.FloatField(default=0.0)),
                ('create_accuracy', models.FloatField(default=0.0)),
                ('weak_topics', models.JSONField(default=dict)),
                ('competency_level', models.CharField(default='Beginner', max_length=50)),
                ('recommend_difficulty', models.FloatField(default=5.0)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendations', models.TextField()),
                ('question_feedback', models.JSONField(default=dict)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('user_quest_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalised_feedback', to='api.userquestattempt')),
            ],
        ),
    ]
