# Generated by Django 5.0.6 on 2025-12-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_cognitive_level_question_difficulty_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerattempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
